public enum Human {
    NONE,
    
    //Bonus
    BONE_BREAK,
    FART,
    FOOD_DRINK,
    FOOD_EAT,
    HEARTBEAT_FAST,
    HEARTBEAT_SLOW,
    
    //Female/High-pitched
    FEMALE_ANGRY,
    FEMALE_BREATH,
    FEMALE_COUGH,
    FEMALE_EFFORT,
    FEMALE_EFFORT_JUMP_AND_FALL,
    FEMALE_FEAR_AND_COLD,
    FEMALE_GRUNT,
    FEMALE_LAUGH,
    FEMALE_SCREAM,
    FEMALE_SIGH,
    FEMALE_THINKING,
    
    //Male/Low-pitched
    MALE_ANGRY,
    MALE_BREATH,
    MALE_COUGH,
    MALE_EFFORT,
    MALE_EFFORT_JUMP_AND_FALL,
    MALE_FEAR_AND_COLD,
    MALE_GRUNT,
    MALE_LAUGH,
    MALE_SCREAM,
    MALE_SIGH,
    MALE_THINKING,
    
}